name: main CI
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello Samriddhi
    steps:
      - name: Hello Samriddhi action step
        id: hello
        uses: octocat/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Samriddhi'
      # Use the output from the `hello` step
      - name: Hello Samriddhi
        run: echo "The time was ${{ steps.hello.outputs.time }}"
